### ISSUE TITLE
Issues about the pre-training code: "img_id2idx_train.json" couldn't be obtained

### ISSUE THREAD

**Issue by leyi-123** [aurooj/WSG-VQA-VLTransformers#2]
Hello, when I reproduced the pre-training code and ran the "bash run/2stage_fulldata_no_init_16_caps.bash" command, I found that the data file "img_id2idx_train.json" is needed, which is in line 91 in src/utils.py. I wonder how this file was obtained. Thanks for your reply.

**Comment by zxzhou9** [comment]
I meet the same problem. Have you ever solved it?

**Comment by aurooj** [comment]
Hello, I have uploaded the required files `img_id2idx_train.json` and `img_id2idx_valid.json` under data_files/ directory on github repo. Thanks for your patience.

**Comment by zxzhou9** [comment]
Thank you so much! Really appreciate that.

**Comment by zxzhou9** [comment]
Sorry to bother you again, I find the gqa_sqatial_merged_info.json can not be found too. Could you upload it later?

**Comment by aurooj** [comment]
Hi! You can download and preprocess the GQA dataset from their [official github repo](https://github.com/stanfordnlp/mac-network/tree/gqa). Follow instructions for `Pre-processing` section will yield you `gqa_sqatial_merged_info.json` file. 

I hope it helps.
